### ISSUE TITLE
Refine Kriging Parameters

### ISSUE THREAD

**Issue by gbrunner** [dnixon1981/STL_Crime_Analysis#4]
@dnixon1981 Recommend you refine your Kriging parameters. Suggest that:
- Use smaller search radius
- Use smaller cell size
- Experiment with semivariogram type.

When you present your results in a few weeks, it might be interesting to show the semivariogram and try to explain it. I can help with this if you need it.

**Comment by dnixon1981** [comment]
Think I was able to knock out most all of the issues.  I was really impressed by the Kriging results that come from the default values
